config/routes.rb
Rails.application.routes.draw do
  get 'topseller/main'
  post 'topseller/main'
  post 'topseller/organ'
  
  get 'my_market', to: 'myinven#main', as: 'my_market_main'
  # post 'my_market'
  post 'my_market/buy1', to: 'myinven#buy1'
  # get 'my_market/buy1'
  
  get '/sale_history', to: 'myinven#sale_history'
  get '/purchase_history', to: 'myinven#purchase_history'

  get 'profile/main'
  post 'profile/main'
  
  root 'main#welcome'
  #root 'main#login'
  post 'profile/password'

  get 'user/main' # where admin sees all users
  post 'user/user_manage'
  get 'user/user_manage'
  get 'user/edit'
  get 'user/new'

  get 'main/home', as: 'main_home'  # the dashboard of each users
  post 'main/home'
  post 'main/log_out'
  post 'shop/item_manage'
  get 'shop/main'
  post 'shop/main'
  get 'main/inventories'
  post 'main/inventories'

  get 'item', to: 'item#index', as: 'item_index'
  get 'item/new', as: 'new_item'
  get 'item/edit', as: 'edit_item'
  get 'item/:id', to: 'item#show', as: 'show_item'
  post 'item/set_enable', to: 'item#set_enable', as: 'set_enable'

  get 'my_inventory', to: 'market#index', as: 'my_inventory'
  get 'my_inventory/new', to: 'market#new', as: 'new_my_inventory'
  post 'my_inventory/create', to: 'market#create', as: 'create_my_inventory'
  get 'my_inventory/edit', to: 'market#edit', as: 'edit_my_inventory'
  post 'my_inventory/update', to: 'market#update', as: 'update_my_inventory'
  delete 'my_inventory/destroy/:id', to: 'market#destroy', as: 'destroy_my_inventory'
  # get 'market/show'

  get 'main/login'
  post 'main/login'
  get 'main/user_item'
  post 'main/user_item'
  post 'main/register'
  get 'main/register'
  post 'main/user_manage'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :Inventory,  :dependent => :destroy
  has_many :Market,  :dependent => :destroy
  has_one_attached :picture do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  before_action :must_logged_in_as_admin
  before_action :set_item, only: %i[ show ]
  def new
    @User = params[:Username]
  end
  def edit
    @Item = params[:item_id]
    Item.connection
    @item = Item.find_by id: params['item_id']

    @name = @item.name
    @category = @item.category
    @enable = @item.enable
    @lock_version = @item.lock_version
    # @price = @item.price
    # @stock = @item.stock

  end

  def index
    @items = Item.all
    # puts '-indexjaaa'
  end

  def set_enable
    item = Item.find_by id: params['item_id']
    if item.nil?
      redirect_to item_index_path, notice: "The item no longer existed" and return
    end

    # check first if the lock_version is okay, otherwise notify the admin of the updated value
    if item.lock_version == params[:lock_version].to_i
      item.update(enable: params['enable'].to_s)
      redirect_to item_index_path, notice: "Update success"
      return
    else
      redirect_to item_index_path, notice: "Update Error. Other admins are also editing, please check the updated value first"
      return
    end
  end

  def show

  end

  private
  
  def set_item
    @item = Item.find_by id:params[:id]
    if @item.nil?
      redirect_to item_index_path, notice: "The item no longer existed"
    end
  end

end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/item/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>ID:</strong>
    <%= item.id %>
  </p>
  
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= item.category %>
  </p>
  <% if item.picture.attached? %>
      <%= image_tag rails_blob_path(item.picture.variant(resize_to_limit: [100, 100]), disposition: :attachment) %>
  <% else %>
      <%= image_tag "nopic.png", :size => "100"%>
  <% end %>

</div>

app/views/item/edit.html.erb
<h1>Item Edit</h1>
<% if @item.errors.any? %>
    <div style="color: red">
        <h2><%= pluralize( @item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% @item.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<%= form_with url: '/main/user_manage', method: :post, data:{turbo:false} do |form| %>
    <%= form.label :query, "Name:" %>
    <%= form.text_field "name",:value => @name,:required=>'required'%><br>
    <%= form.label :query, "category" %>
    <%= form.text_field "category",:value =>@category,:required=>'required' %>
    <br>
    <%= form.label :enable, "Enable" %>
    <%= form.radio_button "enable", 'yes', checked: @enable %>Yes
    <%= form.radio_button "enable", 'no', checked: !@enable %>No
    <br>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture %>
    <%= form.hidden_field :item_id, value:@Item%>
    <%= form.hidden_field :lock_version, value: @lock_version %>
    <%= form.submit "Done" %>
<% end %>

<%= link_to "CANCEL", item_index_path %>

app/views/item/index.html.erb
<h1>All Items</h1>

<% if @items.size ==0 %>
<div class="d-flex justify-content-center align-items-center bg-info text-white ">
    <p class="my-2">No data available in table</p>
</div>
<%else%>
<table id='items' class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Enable</th>
            <th>Picture</th>
            <th></th><!-- for datatable -->
            <th></th><!-- for datatable -->
        </tr>
    </thead>
    <tbody>
        <!--
            <% if @items.size == 0 %>
                <tr><td>no items</td></tr>
            <% end %>
        -->
        <% @items.each do |item| %>
            <tr>
                <td><%= item.id %></td>
                <td><%= item.name %></td>
                <td><%= item.category %></td>
                <td><%= item.enable %></td>
                <td>
                    <% if item.picture.attached? %>
                        <%= image_tag rails_blob_path(item.picture.variant(:thumb), disposition: :attachment) %>
                    <% else %>
                        <%= image_tag "nopic.png", :size => "100"%>
                    <% end %>
                </td>
                <% if item.enable %>
                  <td><%= button_to "Disable", set_enable_path(item_id: item.id, enable: false, lock_version: item.lock_version), method: :post, class: 'btn btn-danger'%></td>
                <% else %>
                  <td><%= button_to "Enable", set_enable_path(item_id: item.id, enable: true, lock_version: item.lock_version), method: :post, class: 'btn btn-success'%></td>
                <% end %>
                <td><%= link_to "Show", show_item_path(item.id), class: 'btn btn-primary' %></td>
            </tr>
        <% end %>

    </tbody>
</table>
<% end %>
<%= link_to "New", new_item_path, class: 'btn btn-primary' %>


<script>
    $(document).ready( function () {
        $('#items').DataTable();
    });
</script>

app/views/item/new.html.erb
<h1>New Item</h1>
<%=@User%>
<%= form_with url: '/main/user_manage', method: :post, data:{turbo:false} do |form| %>
    <%= form.label :name, "Name:" %>
    <%= form.text_field "name",:value => params["name"],:required=>'required', class: "form-control" %><br>
    <%= form.label :category, "Category:" %>
    <%= form.text_field "category",:value =>@category,:required=>'required', class: "form-control" %>
    <br>
    <%= form.label :enable, "Enable:" %>
    <br>
    <%= form.radio_button "enable", 'yes', class: "form-check-input mx-2", checked: true %>Yes
    <%= form.radio_button "enable", 'no', class: "form-check-input mx-2" %>No
    <br>
    <br>
    <%= form.label :picture, "Picture (Optional):", style: "display: block", class: 'formFileLg' %>
    <br>
    <%= form.file_field :picture, class: 'form-control form-control-sm' %>
    <br>
    <%= form.hidden_field :username,value:@User%>
    <br>
    <div class='row'>
        <div class='col'>
            <%= form.submit "Create", class: 'btn btn-primary' %>
        </div>
        <div class='col'>
            <%= link_to "Cancel", item_index_path, class: 'btn btn-secondary' %>
        </div>
    </div>
<% end %>

app/views/item/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render partial: "item/item", :locals =>{item: @item} %>

<div>
    <%= form_with url: '/main/user_manage', method: 'post', data: {turbo:false} do |form| %>
        <%= form.hidden_field :item_id, value: @item.id%>    
        <%= form.submit "Edit",:class=>'btn btn-primary my-1'%>
    <%end%>

    <%= form_with url: '/main/user_manage', method: 'post', data: {turbo:false} do |form| %>
        <%= form.hidden_field :item_id,value:@item.id%>
        <%= form.submit "Delete",:class=>'btn btn-danger my-1'%>

    <%end%>
    <%= link_to "Back to items", item_index_path, class: 'btn btn-primary my-1' %>
</div>