config/routes.rb
Rails.application.routes.draw do
  get 'topseller/main'
  post 'topseller/main'
  post 'topseller/organ'
  
  get 'my_market', to: 'myinven#main', as: 'my_market_main'
  # post 'my_market'
  post 'my_market/buy1', to: 'myinven#buy1'
  # get 'my_market/buy1'
  
  get '/sale_history', to: 'myinven#sale_history'
  get '/purchase_history', to: 'myinven#purchase_history'

  get 'profile/main'
  post 'profile/main'
  
  root 'main#welcome'
  #root 'main#login'
  post 'profile/password'

  get 'user/main' # where admin sees all users
  post 'user/user_manage'
  get 'user/user_manage'
  get 'user/edit'
  get 'user/new'

  get 'main/home', as: 'main_home'  # the dashboard of each users
  post 'main/home'
  post 'main/log_out'
  post 'shop/item_manage'
  get 'shop/main'
  post 'shop/main'
  get 'main/inventories'
  post 'main/inventories'

  get 'item', to: 'item#index', as: 'item_index'
  get 'item/new', as: 'new_item'
  get 'item/edit', as: 'edit_item'
  get 'item/:id', to: 'item#show', as: 'show_item'
  post 'item/set_enable', to: 'item#set_enable', as: 'set_enable'

  get 'my_inventory', to: 'market#index', as: 'my_inventory'
  get 'my_inventory/new', to: 'market#new', as: 'new_my_inventory'
  post 'my_inventory/create', to: 'market#create', as: 'create_my_inventory'
  get 'my_inventory/edit', to: 'market#edit', as: 'edit_my_inventory'
  post 'my_inventory/update', to: 'market#update', as: 'update_my_inventory'
  delete 'my_inventory/destroy/:id', to: 'market#destroy', as: 'destroy_my_inventory'
  # get 'market/show'

  get 'main/login'
  post 'main/login'
  get 'main/user_item'
  post 'main/user_item'
  post 'main/register'
  get 'main/register'
  post 'main/user_manage'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/market.rb
class Market < ApplicationRecord
    belongs_to :seller, :class_name => 'User', :foreign_key => 'seller_id'
    belongs_to :item, :class_name => 'Item',:foreign_key => 'item_id'
    def get_item_name
        Item.find(self.item_id).name
    end

    def get_item_category
        Item.find(self.item_id).category
    end

    def is_enable
        Item.find(self.item_id).enable
    end

    def is_disable
        !self.is_enable
    end


end

app/controllers/market_controller.rb
# this class handles the /my_inventory routes
# but handles the Market Model

class MarketController < ApplicationController
  before_action do
    must_logged_in_as_one_of [0, 1] # must be roles admin(0), or seller(1) to access
  end

  def index # for displaying /my_market
    @items = Item.all.select {|i| i.enable}

    whoare = User.find_by(username: session["username"]).id
    @markets = Market.where(seller_id: whoare).select {|m| m.is_enable}
  end

  def show
  end

  def new
    @item_for_new_market = Item.find(params[:item_id])
    
    # if admin has blocked
    if @item_for_new_market.enable == false
      redirect_to my_inventory_path, notice:'admin ห้ามขายแล้วจ้า ขอโทดน้า'
    end
  end

  def create
    # if not seller redirect to their home
    if session[:usertype] != 1
      redirect_to my_inventory_path, notice:'must be seller to add items for sell'
    end

    # if admin has blocked
    if Item.find(params[:item_id]).enable == false
      redirect_to my_inventory_path, notice:'admin ห้ามขายแล้วจ้า ขอโทดน้า'
      return
    end

    @market = Market.new(
      item_id: params[:item_id],
      price: params[:price].to_d,
      stock: params[:stock].to_i,
      seller_id: whoare = User.find_by(username: session["username"]).id
    )

    respond_to do |format|
      if @market.save
        format.html { redirect_to my_inventory_path, notice: "Market was successfully created." }
      else
        # format.html { render :index, status: :unprocessable_entity }
      end
    end

  end
  
  def edit
    @market = Market.find_by id: params[:market_id]

    if @market.nil?
      redirect_to my_inventory_path, notice:'the associated item or the market is already deleted'
      return
    end

    # if admin has blocked
    if @market.is_disable
      redirect_to my_inventory_path, notice:'admin ห้ามขายแล้วจ้า ขอโทดน้า'
      return
    end

    
  end

  def update
    @market = Market.find_by id: params[:market_id]

    if @market.nil?
      redirect_to my_inventory_path, notice:'the associated item or the market is already deleted'
      return
    end

    # if admin has blocked
    if @market.is_disable
      redirect_to my_inventory_path, notice:'admin ห้ามขายแล้วจ้า ขอโทดน้า'
      return
    end

    respond_to do |format|
      if @market.update(price: params[:price].to_d, stock: params[:stock].to_i)
        format.html { redirect_to my_inventory_path, notice: "Market was successfully updated." }
      else
        # format.html { render :index, status: :unprocessable_entity }
      end
    end

  end

  def destroy

    @market = Market.find_by id: params[:id]

    if @market.nil?
      redirect_to my_inventory_path, notice:'the associated item or the market is already deleted'
      return
    end

    # if admin has blocked
    if @market.is_disable
      redirect_to my_inventory_path, notice:'admin ห้ามขายแล้วจ้า ขอโทดน้า'
      return
    end

    @market.destroy
    redirect_to my_inventory_path, notice: "Market was successfully destroyed."
  end

  

end

app/helpers/market_helper.rb
module MarketHelper
end

app/views/market/edit.html.erb
<h1>Market#edit</h1>
<p>Find me in app/views/market/edit.html.erb</p>
<h3>Item_ID</h3>
<p><%= @market.item_id %></p>

<h3>Name</h3>
<p><%= @market.get_item_name %></p>

<h3>Category</h3>
<p><%= @market.get_item_category %></p>

<h3>Image</h3>
<% if @market.item.picture.attached? %>
      <%= image_tag rails_blob_path(@market.item.picture.variant(resize_to_limit: [100, 100]), disposition: :attachment) %>
<% else %>
    <%= image_tag "nopic.png", :size => "100"%>
<% end %>

<%= form_with url: update_my_inventory_path, method: 'post',data: {turbo:false} do |form| %>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, value: @market.price %>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock, in: 0...10000, value: @market.stock %>

    <%= form.hidden_field :market_id, value: @market.id  %>
    <%= form.submit "CONFIRM" %>
<% end %>

<%= link_to "CANCEL", my_inventory_path %>

app/views/market/index.html.erb
<% if session[:usertype] == 1%>
    <h2>My Inventories</h2>
    <% if @markets.size ==0 %>
    <div class="d-flex justify-content-center align-items-center bg-info text-white ">
        <p class="my-2">No data available in table</p>
    </div>
    <%else%>
        <table id='markets' class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Item_ID</th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Picture</th>
                        <th>Price</th>
                        <th>Stock</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @markets.each do |m| %>
                        <tr>
                            <td><%= m.item_id %></td>
                            <td><%= m.get_item_name %></td>
                            <td><%= m.get_item_category %></td>
                            <td>
                                <% if m.item.picture.attached? %>
                                    <%= image_tag rails_blob_path(m.item.picture.variant(:thumb), disposition: :attachment) %>
                                <% else %>
                                    <%= image_tag "nopic.png", :size => "100"%>
                                <% end %>
                            </td>
                            <td><%= m.price %></td>
                            <td><%= m.stock %></td>
                            <td><%= link_to "EDIT", edit_my_inventory_path(market_id: m.id), class: 'btn btn-primary' %></td>
                            <td><%= button_to "Delete", destroy_my_inventory_path(id: m.id), method: :delete, class: 'btn btn-danger' %></td>
                            
                        </tr>
                    <% end %>
                    <!-- 
                    <% if @markets.size == 0 %>
                        <tr>
                            <td>nothing to display</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    <% end %>
                    -->
                </tbody>
        </table>
    <% end %>
    <br>
<% end %>

<h2>All Items</h2>
<% if @items.size ==0 %>
<div class="d-flex justify-content-center align-items-center bg-info text-white ">
    <p class="my-2">No data available in table</p>
</div>
<%else%>
<table id='items' class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Item_ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Picture</th>
            
            <% if session[:usertype] == 1 %>
                <th></th> <!-- for datatable -->
            <% end %>
        </tr>
    </thead>
    <tbody>

        <% @items.each do |i| %>
            <tr>
                <td><%= i.id %></td>
                <td><%= i.name %></td>
                <td><%= i.category %></td>
                <td>
                    <% if i.picture.attached? %>
                        <%= image_tag rails_blob_path(i.picture.variant(:thumb), disposition: :attachment) %>
                    <% else %>
                        <%= image_tag "nopic.png", :size => "100"%>
                    <% end %>
                </td>
                <% if session[:usertype] == 1 %>
                    <td><%= link_to "SELL THIS", new_my_inventory_path(item_id: i.id), class: 'btn btn-primary' %></td>
                <% end %>
            </tr>
        <% end %>

    </tbody>
</table>
<% end %>

<script>
    $(document).ready( function () {
        if ($('#markets').length) {
            $('#markets').DataTable();
        }
        $('#items').DataTable();
    });
</script>

app/views/market/new.html.erb
<h1>Market#new</h1>
<p>Find me in app/views/market/new.html.erb</p>
<h3>Item_ID</h3>
<p><%= @item_for_new_market.id %></p>

<h3>Name</h3>
<p><%= @item_for_new_market.name %></p>

<h3>Category</h3>
<p><%= @item_for_new_market.category %></p>

<h3>Image</h3>
<% if @item_for_new_market.picture.attached? %>
      <%= image_tag rails_blob_path(@item_for_new_market.picture.variant(resize_to_limit: [100, 100]), disposition: :attachment) %>
<% else %>
    <%= image_tag "nopic.png", :size => "100"%>
<% end %>


<%= form_with url: create_my_inventory_path, method: 'post',data: {turbo:false} do |form| %>
        <%= form.label :price, style: "display: block" %>
        <%= form.text_field :price, class: 'form-control' %>
        <%= form.label :stock, style: "display: block" %>
        <%= form.number_field :stock, in: 0...10000, class: 'form-control' %>

    <%= form.hidden_field :item_id, value: @item_for_new_market.id  %>
        <%= form.submit "CONFIRM", class: 'btn btn-primary my-1' %>
<% end %>

<%= link_to "CANCEL", my_inventory_path, class: 'btn btn-secondary' %>
 