config/routes.rb
Rails.application.routes.draw do
  get 'topseller/main'
  post 'topseller/main'
  post 'topseller/organ'
  
  get 'my_market', to: 'myinven#main', as: 'my_market_main'
  # post 'my_market'
  post 'my_market/buy1', to: 'myinven#buy1'
  # get 'my_market/buy1'
  
  get '/sale_history', to: 'myinven#sale_history'
  get '/purchase_history', to: 'myinven#purchase_history'

  get 'profile/main'
  post 'profile/main'
  
  root 'main#welcome'
  #root 'main#login'
  post 'profile/password'

  get 'user/main' # where admin sees all users
  post 'user/user_manage'
  get 'user/user_manage'
  get 'user/edit'
  get 'user/new'

  get 'main/home', as: 'main_home'  # the dashboard of each users
  post 'main/home'
  post 'main/log_out'
  post 'shop/item_manage'
  get 'shop/main'
  post 'shop/main'
  get 'main/inventories'
  post 'main/inventories'

  get 'item', to: 'item#index', as: 'item_index'
  get 'item/new', as: 'new_item'
  get 'item/edit', as: 'edit_item'
  get 'item/:id', to: 'item#show', as: 'show_item'
  post 'item/set_enable', to: 'item#set_enable', as: 'set_enable'

  get 'my_inventory', to: 'market#index', as: 'my_inventory'
  get 'my_inventory/new', to: 'market#new', as: 'new_my_inventory'
  post 'my_inventory/create', to: 'market#create', as: 'create_my_inventory'
  get 'my_inventory/edit', to: 'market#edit', as: 'edit_my_inventory'
  post 'my_inventory/update', to: 'market#update', as: 'update_my_inventory'
  delete 'my_inventory/destroy/:id', to: 'market#destroy', as: 'destroy_my_inventory'
  # get 'market/show'

  get 'main/login'
  post 'main/login'
  get 'main/user_item'
  post 'main/user_item'
  post 'main/register'
  get 'main/register'
  post 'main/user_manage'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">My Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Purchase_history</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">My Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Top Seller</a>
        </li>
        <li class="nav-item " >
        <a class="nav-link" style='color:red;' href="#">User Info</a>
      </li>
      <li class="nav-item ">
      <a class="nav-link" style='color:red;'  href="#">Item Info</a>
    </li>
        
     
      </ul>
    
    </div>
  </div>
</nav>

app/views/layouts/_navbar0.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/main/home">Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/profile/main">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/my_market">My Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/purchase_history">Purchase History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sale_history">Sale History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/my_inventory">My Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/topseller/main">Top Seller</a>
        </li>
        <li class="nav-item " >
        <a class="nav-link" style='color:red;' href="/user/main">User Info</a>
      </li>
      <li class="nav-item ">
      <a class="nav-link" style='color:red;'  href="/item">Item Info</a>
    </li>
    </ul>
    <ul class="navbar-nav ml-auto ">
        <li class="nav-item">
            <%= button_to "Logout", main_log_out_path,:class => 'btn btn-danger',:method => :post %>
        </li>
        
     
      </ul>
    
    </div>
  </div>
</nav>

app/views/layouts/_navbar1.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/main/home">Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/profile/main">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sale_history">Sale History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/my_inventory">My Inventory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/topseller/main">Top Seller</a>
        </li>
        </ul>
        <ul class="navbar-nav ml-auto ">
            <li class="nav-item">
                <%= button_to "Logout", main_log_out_path,:class => 'btn btn-danger',:method => :post %>
            </li>
     
        
     
      </ul>
    
    </div>
  </div>
</nav>

app/views/layouts/_navbar2.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/main/home">Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse  " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto ">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/profile/main">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/my_market">My Market</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/purchase_history">Purchase History</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto ">
          <li class="nav-item">
              <%= button_to "Logout", main_log_out_path,:class => 'btn btn-danger',:method => :post %>
          </li>
      </ul>
    
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    
    <!-- for Datatables-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% User.connection %>
  <% if session[:username] == nil %>
  <% # puts '11111111111111111' %>
  <% else %>
    <% @whoare = User.find_by username: session["username"] %>
  <% end %>
  <% if session[:username] == nil %>

  <% elsif @whoare == nil %>
  <% # puts '2222222222222' %>
  <% else %>
    <%if session[:usertype] == 0 %>
     <%= render 'layouts/navbar0' %>
    <% elsif session[:usertype] == 1 %>
     <%= render 'layouts/navbar1' %>
    <% else %>
     <%= render 'layouts/navbar2' %>
    <% end %>
  <% end %>
  <div class='container'>
  <% flash.each do |type,msg| %>
    <div class="alert alert-info">
      <%= msg %>  <!-- need to somehow fix this so that in /item it displays only once-->
      <%= flash.discard(msg) %>
    </div>
    <%end%>
  
    <%= yield %>
  </div>
  </body>
</html>